### PR TITLE
Redirect migration.

### PR DESCRIPTION
**Pull request by Adnan-cds**
Migrates Redirect entities from the *redirect* module.

Covers the "redirects" part of ticket #16

### CODE REVIEW

**Comment by Adnan-cds** [comment]
By the way, the **redirect** module is not enabled in a default LocalGov installation.  This new migration file for redirect entities mentions the *redirect* module in its **dependencies** section.  This means it cannot be installed in a default install of LocalGov.  I am wondering if I should move **config/install/migrate_plus.migration.localgov_redirect.yml** to **config/optional/migrate_plus.migration.localgov_redirect.yml**

FAO @andybroomfield @stephen-cox

**Comment by andybroomfield** [comment]
@Adnan-cds Will be something we will use quite heavily though, thanks for the migration Adnan, will take a look.

**Comment by stephen-cox** [comment]
> By the way, the **redirect** module is not enabled in a default LocalGov installation. 

We should probably enable it in the profile, but the simplest solution here is to add it as a dependency in the `localgov_legacy_migration,info.yml` file so it gets enabled with the migrations.

**Review by stephen-cox — APPROVED** [review]
Works fine for me :+1:

**Comment by Adnan-cds** [comment]
> but the simplest solution here is to add it as a dependency 

+1.  I have just added the declaration.  I am merging it now.  Feel free to raise any other issues with the Redirect migration and I will look into that on a priority basis.

**Pull request merged**
