### PR TITLE
Campaigns migration

### LINKED ISSUE #17: Migrate campaigns
Campaign paragraphs with direct mapping:

- Box link
- Call out box
- Fact box
- Link (aka Advanced Link)
- Link and summary
- Quote
- Text

Campaign paragraphs without a direct mapping:

- Text (two columns) - Need to migrate into 2 text paragraphs
- Text and image (50/50) - Need to migrate into a text and an image paragraph
- Video - New to migrate video URL into media entity (only 2 of these on Croydon site, none on BHCC)

Page builder paragraphs that are now redundant:

- Box link (Page builder)
- Call out box (Page builder)
- Fact boxes (Page builder)
- Link and summary (Page builder)
- Quote box (Page builder)

### PR DESCRIPTION
**Pull request by stephen-cox**
This provides basic migrations for campaigns. As we're moving to using Layout Paragraphs to provides layout all the structural paragraphs have been ignored and the contents of them added into a single column so the structure will need to be added manually.

It also doesn't migrate the paragraph types that include content and structure (as listed on the issue #17). One options for these would be to remove the structural stuff - that is migrate a text and image into a single text field and migrate left and right text into a single text field - it would then be a content editors job to fix these. Alternatively, a migration that takes a single paragraph entity and creates 2 will need to be written.

This pull requests relies on the file and media migration https://github.com/localgovdrupal/localgov_legacy_migration/pull/20.

The one issue I'm aware of here is the summary field is not being migrated. Should be an easy fix.

Closes #17

### CODE REVIEW

**Comment by andybroomfield** [comment]
Initial check on campaign migration.
Seems to bring over the data ok, at least for simple paragraph.
Only issue seems to be the navigation block is not populated. Not sure if thats an issue with this migration or localgov_campaigns generally.
screencapture-localgov-bhcc-test-covid-19-key-statistics-brighton-hove-2020-10-02-12_10_55

**Comment by stephen-cox** [comment]
Glad to hear the campaigns migration is, generally speaking, working okay.

> Only issue seems to be the navigation block is not populated. Not sure if thats an issue with this migration or localgov_campaigns generally.

This looks to be a theming bug. Inspecting the source of the block shows there's a list of pages,  but they are hidden by the CSS. This doesn't seem to effect my local dev environment, but does effect the 2 migration test sites.

@cjstevens78 Are you aware of a theme bug with the campaign sidebar? Examples can be seen here:
- https://bhcc.localgov.agile.coop/covid-19-key-statistics-brighton-hove
- https://croydon.localgov.agile.coop/croydon-streetspace

**Review by andybroomfield — APPROVED** [review]
Happy to get these changes merged in, and then work on the more complex campaigns as a new issue.

**Comment by cjstevens78** [comment]
@stephen-cox @andybroomfield 

looking at the sidebar bug : it is related to a missing media query in **_campaigns.scss** as follows: 

``@include media-breakpoint-up(md) {
  .collapse.dont-collapse-sm {
    display: block;
    height: auto !important;
    visibility: visible;
  }
}``

This was a fairly recent addition to **localgov_theme** so presumably it didnt make it into the **localgov_theme_bhcc** when it was copied. My first iteration of **localgov_theme_croydon** was copy of **localgov_theme_bhcc** (currently on the test site) ... I have since ditched that and copied  **localgov_theme** instead - so **localgov_theme_croydon** now has this breakpoint. I have also added it to **localgov_theme_bhcc** here: https://github.com/localgovdrupal/localgov_theme_bhcc/commit/07233b15768d15dff5b6da90780a0ac5600c42da

**Pull request merged**
