### PR TITLE
Incremental migration

### PR DESCRIPTION
**Pull request by Adnan-cds**
Once the initial migration is complete, subsequent migration runs should import newer changes made to the **source** entities.  This is not possible while we are explicitly migrating **revision ids**.  The error message says that the revision id for an existing entity cannot be updated.   To reproduce this, try ```drush migrate:import --update --group=localgov_migration``` on the **existing** code. To avoid this, I have dropped the "vid" and "revision_id" fields from various migrations.

Dropping revision ids from Paragraph migrations has its problem given that Entity reference revision fields migrated elsewhere are using the revision ids for Paragraphs.  It's not impossible to fix although not simple.  So this change is limited to non-Paragraph entities only.

Additionally, I have also added the [track_changes](https://www.drupal.org/docs/8/api/migrate-api/migrate-source-plugins/overview-of-migrate-source-plugins#track_changes) key to the non-Paragraph migration files so that updates are fetched during every migration run whether we ask for updates or not.  An alternative to using the *track_changes* key is to do ```drush migrate:import --update --group=localgov_migration```.  But that is slower compared to *track_changes* as all entities are updated regardless of any need to update them.

Special note for the *localgov_redirect* migration.  Updates of this fails however you do it.  To avoid it, I had to use the --sync (i.e. ```drush migrate:import --sync localgov_redirect```) option just for this one migration.

### CODE REVIEW

**Comment by Adnan-cds** [comment]
I should add that the **--sync** option is very similar to the **--update** option.  But apart from updating, it **deletes** any imported item that has also been deleted at source.

A downside to the **--update** option is that it wipes out any changes made to an imported entity in the LocalGov site.  **track_changes** has no such side effects making it a safer choice for incremental updates.

**Comment by stephen-cox** [comment]
I'll test this when I get a chance, but one thing that occurs to me is that we're not just migrating revision IDs but also node IDs,  such like. If content is going to be added to the site between topup migrations then there will be a clash is IDs and the migration will fail for those bits of content. If this is likely to be a problem, we shouldn't migrate IDs at all. This will mean rewriting chunks of the migration because in places we assume the IDs are the same as in the old site instead of looking up the new ID.

**Comment by Adnan-cds** [comment]
> If content is going to be added to the site between topup migrations then there will be a clash is IDs and the migration will fail for those bits of content.

That's right.  For this change, I have delibaretely ignored the scenario where new nodes are added to the target site.

> This will mean rewriting chunks of the migration because in places we assume the IDs are the same as in the old site instead of looking up the new ID.

And this is why I have ignored it.  Redirect records in particular will be much effected.

One work around is to increase the [AUTO INCREMENT](https://dev.mysql.com/doc/refman/5.7/en/example-auto-increment.html) value for the **node** database table: ```mysql> ALTER TABLE tbl AUTO_INCREMENT = 1234;```.  The present AUTO INCREMENT value can be grabbed from ```mysql> SHOW CREATE TABLE node```.  This way, new node ids exclusive to the target site should not clash with new node ids imported from the source site.  But this is a crude solution :)

**Comment by andybroomfield** [comment]
Out of interest, is there a reason why a full rollback and re-import is not considered practical. 
This is the current statergy at BHCC at the moment, be interested to know if there are reasons to change?

**Comment by Adnan-cds** [comment]
> is there a reason why a full rollback and re-import is not considered practical.

Good morning :)  This is of course a valid approach.  In fact, I hope to do a final rollback+re-import tomorrow after deploying all these recent migration changes and then leave it to incremental overnight updates.

I expect incremental migration to help in two ways:
- Far quicker than rollback+re-import.
- Manual changes to **migrated content** do not disappear.

At the same time, you can still do rollback+re-import.

**Comment by Adnan-cds** [comment]
By the way, if this creates difficulty for the BHCC migration then I am more than happy to withdraw this.  So please don't hesitate to ask.

**Comment by andybroomfield** [comment]
In our Drupal 7 to 8 Migration, we had to attempt to preserve node IDs, but this wasn't always possible and needed to avoid overriding content.

This was added as a migration callback
````php
function _bhcc_migrate_d7_callback_node_exists($nid) {
  $node = Node::load($nid);
  return (empty($node) ? $nid : NULL);
}
````
And in the migration yaml
````yaml
nid:
    -
      plugin: callback
      callable: _bhcc_migrate_d7_callback_node_exists
      source: tnid
````

**Comment by stephen-cox** [comment]
@Adnan-cds Just going through merge requests I've been asked to review. Is this something you would like looking at still? I can't see any issues merging this as it is.

**Comment by Adnan-cds** [comment]
> I can't see any issues merging this as it is.

Feel free to approve it then :)

**Review by stephen-cox — APPROVED** [review]
Approved!

**Comment by Adnan-cds** [comment]
Thanks :)

**Pull request merged**
