### PR TITLE
New Migration groups

### LINKED ISSUE #24: Split the migration into seperate groups
Currently the migration is run by executing `drush mim --group=localgov_migration`

This works fine to migrate the full site, however it will be useful to be able to take related content types together, particully if we do an alternative to full campaigns migration for our more complex campaigns.

### PR DESCRIPTION
**Pull request by Adnan-cds**
New group names reflect the LocalGov module structure.  For example, all
Campaign related content types have become part of the localgov_campaigns
Migration group.

Closes #24

### CODE REVIEW

**Comment by stephen-cox** [comment]
I'm not convinced this is the best way to split the migration up. It would still be useful to run the entire migration and splitting everything into groups means you have to run multiple groups (A default Drupal install includes the `default` group that we won't want to run).

Would it be better to [tag migration](https://understanddrupal.com/articles/introduction-migration-dependencies-drupal#tagging-migrations) so that specific migrations can be run by [supplying a tag](https://gitlab.com/drupalspoons/migrate_tools/-/blob/8.x-5.x/src/Commands/MigrateToolsCommands.php#L270) and keep the main grouping as it is?

**Comment by Adnan-cds** [comment]
> Would it be better to tag migration so that specific migrations can be run by supplying a tag and keep the main grouping as it is?

Sounds good to me.  I will leave it to Andy to decide.

FAO @andybroomfield

**Review by andybroomfield — APPROVED** [review]
Only done quick tests but these groups seem fine.
We might have to look at dependencies such as servcice and campaigns and the paragraphs group, but that can happen later, no need to hold this up.

And with that I'm on leave for a week, so see you at 1st December standup.

**Comment by Adnan-cds** [comment]
Have a nice holiday Andy :)  Let's discuss the migration tags once you are back.  I will merge this in the mean time.

**Review by stephen-cox — APPROVED** [review]
Looks fine to me

**Comment by Adnan-cds** [comment]
Thanks Steve.  Merging...

**Pull request merged**
